"""cascade_and_password_resets

Revision ID: 0fc1e7515c93
Revises: 3479189a0c7c
Create Date: 2026-06-15 14:52:14.272160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc1e7515c93'
down_revision: Union[str, Sequence[str], None] = '3479189a0c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('attendance_session_id_fkey'), 'attendance', type_='foreignkey')
    op.drop_constraint(op.f('attendance_student_id_fkey'), 'attendance', type_='foreignkey')
    op.create_foreign_key(None, 'attendance', 'students', ['student_id'], ['student_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance', 'attendance_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('attendance_sessions_staff_id_fkey'), 'attendance_sessions', type_='foreignkey')
    op.drop_constraint(op.f('attendance_sessions_subject_id_fkey'), 'attendance_sessions', type_='foreignkey')
    op.drop_constraint(op.f('attendance_sessions_slot_id_fkey'), 'attendance_sessions', type_='foreignkey')
    op.drop_constraint(op.f('attendance_sessions_class_id_fkey'), 'attendance_sessions', type_='foreignkey')
    op.drop_constraint(op.f('attendance_sessions_created_by_student_id_fkey'), 'attendance_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_sessions', 'classes', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance_sessions', 'students', ['created_by_student_id'], ['student_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance_sessions', 'slots', ['slot_id'], ['slot_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance_sessions', 'subjects', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attendance_sessions', 'staff', ['staff_id'], ['staff_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('batches_course_id_fkey'), 'batches', type_='foreignkey')
    op.create_foreign_key(None, 'batches', 'courses', ['course_id'], ['course_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('classes_batch_id_fkey'), 'classes', type_='foreignkey')
    op.create_foreign_key(None, 'classes', 'batches', ['batch_id'], ['batch_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('courses_department_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'departments', ['department_id'], ['department_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('departments_college_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'colleges', ['college_id'], ['college_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('students_class_id_fkey'), 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'classes', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subject_staff_staff_id_fkey'), 'subject_staff', type_='foreignkey')
    op.drop_constraint(op.f('subject_staff_subject_id_fkey'), 'subject_staff', type_='foreignkey')
    op.create_foreign_key(None, 'subject_staff', 'staff', ['staff_id'], ['staff_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subject_staff', 'subjects', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('subjects_class_id_fkey'), 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'classes', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('timetable_slot_id_fkey'), 'timetable', type_='foreignkey')
    op.drop_constraint(op.f('timetable_class_id_fkey'), 'timetable', type_='foreignkey')
    op.drop_constraint(op.f('timetable_subject_id_fkey'), 'timetable', type_='foreignkey')
    op.create_foreign_key(None, 'timetable', 'classes', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timetable', 'subjects', ['subject_id'], ['subject_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'timetable', 'slots', ['slot_id'], ['slot_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.drop_constraint(None, 'timetable', type_='foreignkey')
    op.create_foreign_key(op.f('timetable_subject_id_fkey'), 'timetable', 'subjects', ['subject_id'], ['subject_id'])
    op.create_foreign_key(op.f('timetable_class_id_fkey'), 'timetable', 'classes', ['class_id'], ['class_id'])
    op.create_foreign_key(op.f('timetable_slot_id_fkey'), 'timetable', 'slots', ['slot_id'], ['slot_id'])
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key(op.f('subjects_class_id_fkey'), 'subjects', 'classes', ['class_id'], ['class_id'])
    op.drop_constraint(None, 'subject_staff', type_='foreignkey')
    op.drop_constraint(None, 'subject_staff', type_='foreignkey')
    op.create_foreign_key(op.f('subject_staff_subject_id_fkey'), 'subject_staff', 'subjects', ['subject_id'], ['subject_id'])
    op.create_foreign_key(op.f('subject_staff_staff_id_fkey'), 'subject_staff', 'staff', ['staff_id'], ['staff_id'])
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key(op.f('students_class_id_fkey'), 'students', 'classes', ['class_id'], ['class_id'])
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_college_id_fkey'), 'departments', 'colleges', ['college_id'], ['college_id'])
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_department_id_fkey'), 'courses', 'departments', ['department_id'], ['department_id'])
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.create_foreign_key(op.f('classes_batch_id_fkey'), 'classes', 'batches', ['batch_id'], ['batch_id'])
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.create_foreign_key(op.f('batches_course_id_fkey'), 'batches', 'courses', ['course_id'], ['course_id'])
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.drop_constraint(None, 'attendance_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_sessions_created_by_student_id_fkey'), 'attendance_sessions', 'students', ['created_by_student_id'], ['student_id'])
    op.create_foreign_key(op.f('attendance_sessions_class_id_fkey'), 'attendance_sessions', 'classes', ['class_id'], ['class_id'])
    op.create_foreign_key(op.f('attendance_sessions_slot_id_fkey'), 'attendance_sessions', 'slots', ['slot_id'], ['slot_id'])
    op.create_foreign_key(op.f('attendance_sessions_subject_id_fkey'), 'attendance_sessions', 'subjects', ['subject_id'], ['subject_id'])
    op.create_foreign_key(op.f('attendance_sessions_staff_id_fkey'), 'attendance_sessions', 'staff', ['staff_id'], ['staff_id'])
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.create_foreign_key(op.f('attendance_student_id_fkey'), 'attendance', 'students', ['student_id'], ['student_id'])
    op.create_foreign_key(op.f('attendance_session_id_fkey'), 'attendance', 'attendance_sessions', ['session_id'], ['session_id'])
    op.drop_table('password_resets')
    # ### end Alembic commands ###
