"""initial schema

Revision ID: 3479189a0c7c
Revises: 
Create Date: 2026-06-12 19:27:27.871347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3479189a0c7c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('college_name', sa.String(length=255), nullable=False),
    sa.Column('college_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('college_id'),
    sa.UniqueConstraint('college_code')
    )
    op.create_table('slots',
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('slot_no', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('staff_code', sa.String(length=50), nullable=False),
    sa.Column('staff_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('staff_code')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('college_id', sa.UUID(), nullable=False),
    sa.Column('department_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.college_id'], ),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('batches',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('batch_start_year', sa.Integer(), nullable=False),
    sa.Column('batch_end_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('classes',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('current_semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('register_no', sa.String(length=50), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('register_no')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('subject_type', sa.String(length=50), nullable=False),
    sa.Column('attendance_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('attendance_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('created_by_student_id', sa.UUID(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['created_by_student_id'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.slot_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('subject_staff',
    sa.Column('mapping_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('is_incharge', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_table('timetable',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.slot_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('timetable_id')
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('od_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.session_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    op.drop_table('timetable')
    op.drop_table('subject_staff')
    op.drop_table('attendance_sessions')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('classes')
    op.drop_table('batches')
    op.drop_table('courses')
    op.drop_table('departments')
    op.drop_table('staff')
    op.drop_table('slots')
    op.drop_table('colleges')
    # ### end Alembic commands ###
