"""add_student_otp_fields

Revision ID: 687f962b3742
Revises: 0fc1e7515c93
Create Date: 2026-06-16 18:47:44.433071

"""
from typing import Sequence, Union

# pyrefly: ignore [missing-import]
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687f962b3742'
down_revision: Union[str, Sequence[str], None] = '0fc1e7515c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('otp_code', sa.String(length=6), nullable=True))
    op.add_column('students', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('otp_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'otp_verified')
    op.drop_column('students', 'otp_expiry')
    op.drop_column('students', 'otp_code')
    # ### end Alembic commands ###
